"use client";
import { useEffect, useMemo, useState } from "react";
import type { SeoReport } from "@/lib/seo/types";

type Site={siteUrl:string;permissionLevel:string};
type Row={keys?:string[];clicks:number;impressions:number;ctr:number;position:number};

const demo=`# 스마트폰 저장 공간이 부족한 이유와 해결 방법\n\n스마트폰을 오래 사용하다 보면 사진과 앱이 쌓이면서 저장 공간이 빠르게 줄어듭니다. 이 글에서는 초보자도 따라 할 수 있는 정리 순서와 안전한 백업 방법을 설명합니다.\n\n## 저장 공간이 줄어드는 대표적인 원인\n사진과 동영상, 메신저 파일, 앱 캐시, 다운로드 파일이 대표적인 원인입니다.\n\n## 먼저 확인할 항목\n설정의 저장 공간 메뉴에서 어떤 항목이 많은 용량을 사용하는지 확인합니다.\n\n## 안전하게 용량을 확보하는 방법\n중요한 사진을 백업하고, 필요 없는 다운로드 파일과 중복 파일을 삭제합니다.`;

function Score({label,value}:{label:string;value:number}){return <div className="seo-score-card"><span>{label}</span><strong>{value}</strong><small>/100</small><div><i style={{width:`${value}%`}}/></div></div>}

export default function SeoStudio(){
 const [title,setTitle]=useState("스마트폰 저장 공간이 부족한 이유와 용량을 늘리는 가장 쉬운 방법 (2026 최신 가이드)");
 const [keyword,setKeyword]=useState("스마트폰 저장 공간"); const [content,setContent]=useState(demo); const [audience,setAudience]=useState("20~40대 스마트폰 사용자"); const [url,setUrl]=useState("");
 const [report,setReport]=useState<SeoReport|null>(null); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const [connected,setConnected]=useState(false); const [sites,setSites]=useState<Site[]>([]); const [site,setSite]=useState(""); const [rows,setRows]=useState<Row[]>([]); const [gscLoading,setGscLoading]=useState(false);
 const dates=useMemo(()=>{const end=new Date();end.setDate(end.getDate()-2);const start=new Date(end);start.setDate(start.getDate()-27);return{start:start.toISOString().slice(0,10),end:end.toISOString().slice(0,10)}},[]);
 useEffect(()=>{fetch("/api/search-console/sites").then(r=>r.json()).then(data=>{setConnected(Boolean(data.connected));setSites(data.sites||[]);setSite(data.sites?.[0]?.siteUrl||"")}).catch(()=>{})},[]);
 async function analyze(){setLoading(true);setMessage("");try{const res=await fetch("/api/seo/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,primaryKeyword:keyword,content,targetAudience:audience,contentUrl:url})});const data=await res.json();if(!res.ok)throw new Error(data.message||"분석 실패");setReport(data.report);setMessage(data.saved?"SEO 분석과 보고서 저장이 완료되었습니다.":"SEO 분석 완료 · SQL 실행 전이라 보고서는 저장되지 않았습니다.");}catch(e){setMessage(e instanceof Error?e.message:"분석 실패")}finally{setLoading(false)}}
 async function loadGsc(){setGscLoading(true);setMessage("");try{const res=await fetch("/api/search-console/performance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({siteUrl:site,startDate:dates.start,endDate:dates.end})});const data=await res.json();if(!res.ok)throw new Error(data.message||"조회 실패");setRows(data.rows||[]);setMessage(`Search Console 최근 28일 데이터 ${data.rows?.length||0}개를 불러왔습니다.`);}catch(e){setMessage(e instanceof Error?e.message:"조회 실패")}finally{setGscLoading(false)}}
 async function disconnect(){await fetch("/api/search-console/disconnect",{method:"POST"});location.reload()}
 const totals=useMemo(()=>rows.reduce((a,r)=>({clicks:a.clicks+r.clicks,impressions:a.impressions+r.impressions}),{clicks:0,impressions:0}),[rows]);
 return <div className="seo-studio-stack">
  {message&&<div className={message.includes("실패")||message.includes("없습니다")?"alert alert-error":"alert alert-success"}>{message}</div>}
  <section className="panel seo-hero"><div><span className="eyebrow">SPRINT 8 · SEO & CONTENT OPTIMIZATION</span><h2>검색성과와 콘텐츠 품질을 한 화면에서 개선합니다.</h2><p>AI 분석은 구조·가독성·클릭 가능성을 점검하고, Search Console은 실제 클릭·노출·CTR·평균순위를 가져옵니다.</p></div><div className="seo-hero-actions"><button className="button button-primary" onClick={analyze} disabled={loading}>{loading?"AI 분석 중...":"SEO 통합 분석 실행"}</button>{connected?<button className="button button-light" onClick={disconnect}>Search Console 연결 해제</button>:<a className="button button-success" href="/api/search-console/start">Google Search Console 연결</a>}</div></section>
  <div className="seo-layout"><section className="panel"><div className="section-head"><div><span className="eyebrow">CONTENT INPUT</span><h2>분석할 콘텐츠</h2></div></div><div className="grid grid-2"><div className="field"><label>SEO 제목</label><input className="input" value={title} onChange={e=>setTitle(e.target.value)}/></div><div className="field"><label>핵심 키워드</label><input className="input" value={keyword} onChange={e=>setKeyword(e.target.value)}/></div><div className="field"><label>타깃 독자</label><input className="input" value={audience} onChange={e=>setAudience(e.target.value)}/></div><div className="field"><label>게시 URL (선택)</label><input className="input" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/></div></div><div className="field"><label>본문</label><textarea className="textarea seo-content-input" value={content} onChange={e=>setContent(e.target.value)}/></div></section>
  <section className="panel"><span className="eyebrow">GOOGLE SEARCH CONSOLE</span><h2>실제 검색 성과</h2>{connected?<><div className="field"><label>Search Console 속성</label><select className="input" value={site} onChange={e=>setSite(e.target.value)}>{sites.map(s=><option key={s.siteUrl} value={s.siteUrl}>{s.siteUrl} · {s.permissionLevel}</option>)}</select></div><button className="button button-primary" onClick={loadGsc} disabled={gscLoading||!site}>{gscLoading?"성과 조회 중...":"최근 28일 성과 불러오기"}</button><div className="grid grid-2" style={{marginTop:16}}><div className="stat"><small>총 클릭</small><strong>{Math.round(totals.clicks).toLocaleString()}</strong></div><div className="stat"><small>총 노출</small><strong>{Math.round(totals.impressions).toLocaleString()}</strong></div></div></>:<div className="empty"><strong>아직 연결되지 않았습니다.</strong><p>OAuth 연결 후 인증된 사이트 목록과 검색 실적을 자동으로 가져옵니다.</p><a className="button button-success" href="/api/search-console/start">Search Console 연결 시작</a></div>}</section></div>
  {report&&<><section className="panel"><div className="section-head"><div><span className="eyebrow">SEO SCORE</span><h2>콘텐츠 종합 점수</h2></div></div><div className="seo-score-grid"><Score label="종합" value={report.scores.overall}/><Score label="제목" value={report.scores.title}/><Score label="본문" value={report.scores.content}/><Score label="키워드" value={report.scores.keyword}/><Score label="가독성" value={report.scores.readability}/><Score label="예상 CTR" value={report.scores.ctr}/><Score label="구조" value={report.scores.structure}/></div></section>
  <div className="seo-layout"><section className="panel"><span className="eyebrow">META & KEYWORDS</span><h2>{report.metaTitle}</h2><p>{report.metaDescription}</p><div className="badges">{report.keywords.map(k=><span className="badge" key={k}>{k}</span>)}</div><h3>추천 목차</h3><ol className="seo-list">{report.headings.map(h=><li key={h}>{h}</li>)}</ol></section><section className="panel"><span className="eyebrow">AI IMPROVEMENTS</span><h2>우선 개선 제안</h2><ol className="seo-list seo-priority">{report.improvements.map(x=><li key={x}>{x}</li>)}</ol><h3>잘된 점</h3><ul className="seo-list">{report.strengths.map(x=><li key={x}>{x}</li>)}</ul></section></div>
  <section className="panel"><span className="eyebrow">THUMBNAIL A/B/C</span><h2>클릭을 유도하는 썸네일 기획안</h2><div className="grid grid-3">{report.thumbnails.map(v=><article className="thumbnail-plan" key={v.label}><div className="thumbnail-letter">{v.label}</div><strong>{v.headline}</strong><p>{v.subline}</p><small>{v.visualDirection}</small><div className="thumbnail-ctr">예상 CTR 점수 <b>{v.predictedCtr}</b></div></article>)}</div></section>
  <div className="seo-layout"><section className="panel"><span className="eyebrow">SHORTS OPTIMIZER</span><h2>{report.shorts.title}</h2><div className="seo-copy-block"><b>훅</b><p>{report.shorts.hook}</p></div><div className="seo-copy-block"><b>15~30초 대본</b><p>{report.shorts.script}</p></div><div className="seo-copy-block"><b>CTA</b><p>{report.shorts.cta}</p></div><div className="badges">{report.shorts.hashtags.map(x=><span className="badge" key={x}>{x}</span>)}</div></section><section className="panel"><span className="eyebrow">FAQ & LINK IDEAS</span><h2>검색 의도를 넓히는 보강 자료</h2>{report.faq.map(f=><details key={f.question}><summary>{f.question}</summary><p>{f.answer}</p></details>)}<h3>내부 링크</h3><ul className="seo-list">{report.internalLinkIdeas.map(x=><li key={x}>{x}</li>)}</ul><h3>이미지 ALT</h3><ul className="seo-list">{report.altTexts.map(x=><li key={x}>{x}</li>)}</ul></section></div></>}
  {rows.length>0&&<section className="panel"><span className="eyebrow">SEARCH PERFORMANCE</span><h2>검색어·페이지 성과 TOP 50</h2><div className="table-wrap"><table><thead><tr><th>검색어</th><th>페이지</th><th>클릭</th><th>노출</th><th>CTR</th><th>순위</th></tr></thead><tbody>{rows.slice(0,50).map((r,i)=><tr key={`${r.keys?.join("-")}-${i}`}><td>{r.keys?.[0]||"-"}</td><td className="seo-url-cell">{r.keys?.[1]||"-"}</td><td>{r.clicks.toFixed(0)}</td><td>{r.impressions.toFixed(0)}</td><td>{(r.ctr*100).toFixed(1)}%</td><td>{r.position.toFixed(1)}</td></tr>)}</tbody></table></div></section>}
 </div>
}
