"use client";
import { useEffect, useState } from "react";

type Project = { id:string; title:string; product_name:string; duration_seconds:number; ratio:string; style:string; status:string; final_video_url?:string|null; created_at:string };
type Scene = { id:string; scene_number:number; start_second:number; end_second:number; role:string; prompt:string; subtitle_text:string; narration:string; status:string; video_url?:string|null; error_message?:string|null };

const styles = [
  ["cinematic-product","영화형 상품 광고"],["emotional-brand","감성 브랜드"],["how-to","사용법 설명"],["ugc-review","후기형 UGC"],["problem-solution","문제 해결형"],
];

export default function CreativeStudioPro(){
  const [form,setForm]=useState({title:"GY-NEXUS 25초 상품 영상",productName:"",productDescription:"",masterPrompt:"첫 2초는 강한 시각적 훅, 실제 사용 장면 중심, 과장 없는 프리미엄 광고",sourceImageUrl:"",duration:25,ratio:"720:1280",style:"cinematic-product",subtitleMode:"korean",voiceMode:"female",musicMood:"modern-corporate"});
  const [projects,setProjects]=useState<Project[]>([]); const [selected,setSelected]=useState<Project|null>(null); const [scenes,setScenes]=useState<Scene[]>([]);
  const [busy,setBusy]=useState<"create"|"scene"|"all"|"render"|null>(null); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const completed=scenes.filter(s=>s.status==="completed").length; const progress=scenes.length?Math.round(completed/scenes.length*100):0;
  async function loadProjects(){const r=await fetch("/api/creative-studio-pro/projects",{cache:"no-store"});const d=await r.json();if(d.success)setProjects(d.projects)}
  async function openProject(project:Project){setSelected(project);setError("");const r=await fetch(`/api/creative-studio-pro/projects/${project.id}`,{cache:"no-store"});const d=await r.json();if(d.success){setSelected(d.project);setScenes(d.scenes)}else setError(d.message)}
  useEffect(()=>{loadProjects()},[]);
  function patch(key:string,value:string|number){setForm(v=>({...v,[key]:value}))}
  async function createProject(){setBusy("create");setError("");setMessage("");try{const r=await fetch("/api/creative-studio-pro/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message);setMessage(`${d.scenes.length}개 장면 기획이 완료되었습니다.`);await loadProjects();await openProject(d.project)}catch(e){setError(e instanceof Error?e.message:"프로젝트 생성 실패")}finally{setBusy(null)}}
  async function generateNext(silent=false){if(!selected)return false; if(!silent){setBusy("scene");setError("");setMessage("")}try{const r=await fetch(`/api/creative-studio-pro/projects/${selected.id}/generate-next`,{method:"POST"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message);await openProject(selected);if(!silent)setMessage(d.done?"모든 장면 생성이 완료되었습니다.":"다음 장면 생성이 완료되었습니다.");return !!d.done}catch(e){setError(e instanceof Error?e.message:"장면 생성 실패");return true}finally{if(!silent)setBusy(null)}}
  async function generateAll(){if(!selected)return;setBusy("all");setError("");setMessage("장면을 순서대로 생성하고 있습니다. 창을 닫지 마세요.");for(let i=0;i<scenes.length+1;i++){const done=await generateNext(true);if(done)break;}await openProject(selected);setBusy(null);setMessage("장면 일괄 생성 작업을 마쳤습니다.")}
  async function render(){if(!selected)return;setBusy("render");setError("");setMessage("");try{const r=await fetch(`/api/creative-studio-pro/projects/${selected.id}/render`,{method:"POST"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message);setMessage(d.message)}catch(e){setError(e instanceof Error?e.message:"렌더링 요청 실패")}finally{setBusy(null)}}
  return <div className="creative-pro-stack">
    <section className="panel creative-pro-hero"><div><div className="eyebrow">CREATIVE STUDIO PRO · MULTI-SHOT</div><h1>20·25·30초 자체 영상 제작센터</h1><p>길이와 스타일을 선택하면 Dream Y가 5초 장면으로 자동 기획하고, Runway로 장면별 영상을 만든 뒤 FFmpeg Worker가 자막·음성·음악을 합성합니다.</p></div><div className="creative-pro-badge"><strong>{form.duration}초</strong><span>{form.duration/5}개 장면</span></div></section>
    <div className="creative-pro-layout"><section className="panel creative-pro-form"><h2>1. 영상 설정</h2><div className="form-grid"><label>작업명<input value={form.title} onChange={e=>patch("title",e.target.value)}/></label><label>상품명<input value={form.productName} onChange={e=>patch("productName",e.target.value)} placeholder="예: USB-C 8포트 허브"/></label></div><label>상품 설명<textarea rows={4} value={form.productDescription} onChange={e=>patch("productDescription",e.target.value)} placeholder="핵심 장점, 사용 대상, 사용 상황"/></label><label>공통 연출 지시<textarea rows={4} value={form.masterPrompt} onChange={e=>patch("masterPrompt",e.target.value)}/></label><label>첫 장면 이미지 URL<input value={form.sourceImageUrl} onChange={e=>patch("sourceImageUrl",e.target.value)} placeholder="선택사항 · HTTPS 공개 이미지"/></label>
      <div className="choice-block"><b>영상 길이</b><div className="choice-row">{[20,25,30].map(n=><button key={n} className={form.duration===n?"selected":""} onClick={()=>patch("duration",n)}>{n}초</button>)}</div></div>
      <div className="form-grid"><label>스타일<select value={form.style} onChange={e=>patch("style",e.target.value)}>{styles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>화면 비율<select value={form.ratio} onChange={e=>patch("ratio",e.target.value)}><option value="720:1280">9:16 쇼츠</option><option value="1280:720">16:9 유튜브</option></select></label><label>자막<select value={form.subtitleMode} onChange={e=>patch("subtitleMode",e.target.value)}><option value="korean">정확한 한국어 자막</option><option value="none">자막 없음</option></select></label><label>음성<select value={form.voiceMode} onChange={e=>patch("voiceMode",e.target.value)}><option value="female">여성 내레이션</option><option value="male">남성 내레이션</option><option value="music-only">배경음악만</option><option value="silent">무음</option></select></label></div>
      <div className="cost-note"><b>생성 전 안내</b><span>예상 {form.duration/5}개 클립 · 모델별 실제 API 크레딧은 Runway 요금에 따라 달라집니다.</span></div><button className="button button-primary" onClick={createProject} disabled={!!busy}>{busy==="create"?"기획 저장 중...":"장면 기획 프로젝트 만들기"}</button>{message&&<p className="success-text">{message}</p>}{error&&<p className="error-text">{error}</p>}</section>
      <section className="panel creative-pro-projects"><h2>최근 프로젝트</h2>{projects.length===0?<p className="empty-state">아직 프로젝트가 없습니다.</p>:projects.map(p=><button key={p.id} onClick={()=>openProject(p)} className={selected?.id===p.id?"project-item active":"project-item"}><span><b>{p.title}</b><small>{p.product_name} · {p.duration_seconds}초</small></span><em>{p.status}</em></button>)}</section></div>
    {selected&&<section className="panel creative-pro-timeline"><div className="timeline-head"><div><span className="eyebrow">PROJECT</span><h2>{selected.title}</h2><p>{completed}/{scenes.length} 장면 완료</p></div><div className="timeline-actions"><button onClick={()=>generateNext()} disabled={!!busy||completed===scenes.length}>{busy==="scene"?"생성 중...":"다음 장면 생성"}</button><button onClick={generateAll} disabled={!!busy||completed===scenes.length}>{busy==="all"?"전체 생성 중...":"남은 장면 모두 생성"}</button><button className="render" onClick={render} disabled={!!busy||completed!==scenes.length}>{busy==="render"?"요청 중...":"최종 MP4 합성"}</button></div></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div><div className="scene-grid">{scenes.map(scene=><article key={scene.id} className={`scene-card ${scene.status}`}><div className="scene-number">{scene.scene_number}</div><div><b>{scene.start_second}–{scene.end_second}초 · {scene.role}</b><p>{scene.subtitle_text||"자막 없음"}</p><details><summary>장면 프롬프트</summary><small>{scene.prompt}</small></details>{scene.error_message&&<p className="error-text">{scene.error_message}</p>}{scene.video_url&&<video src={scene.video_url} controls playsInline/>}</div><span className="scene-status">{scene.status}</span></article>)}</div>{selected.final_video_url&&<div className="final-preview"><h3>최종 완성 영상</h3><video src={selected.final_video_url} controls playsInline/><a className="button button-primary" href={selected.final_video_url} target="_blank">원본 열기</a></div>}</section>}
  </div>
}
