"use client";
import { useMemo, useState } from "react";
type ContentItem = { id: string; product_title: string; title: string; content: string; content_type: string; created_at: string };
type PublishingJob = { id: string; channel: string; title: string; content: string; status: string; scheduled_at: string; published_at?: string|null; last_error?: string|null; attempts?: number; payload?: { resultUrl?: string|null; resultMessage?: string; naverPackage?: { text?: string }; isDraft?: boolean }|null };
const channels = [{id:"youtube",label:"YouTube"},{id:"blogger",label:"Blogger"},{id:"naver",label:"네이버 블로그"}];
const channelLabel: Record<string,string> = { youtube:"YouTube", blogger:"Blogger", naver:"네이버 블로그", wordpress:"WordPress", webhook:"자동화 웹훅" };
const statusLabel: Record<string,string> = { queued:"대기", processing:"처리 중", published:"완료", retry:"재시도 대기", cancelled:"취소" };
function localDateTimeValue(date=new Date()){ const offset=date.getTimezoneOffset(); return new Date(date.getTime()-offset*60000).toISOString().slice(0,16); }
export default function PublishingCenter({initialJobs,contents}:{initialJobs:PublishingJob[];contents:ContentItem[]}){
 const [jobs,setJobs]=useState(initialJobs); const [selectedChannels,setSelectedChannels]=useState<string[]>(["blogger"]); const [sourceId,setSourceId]=useState(""); const [title,setTitle]=useState(""); const [content,setContent]=useState(""); const [scheduledAt,setScheduledAt]=useState(localDateTimeValue()); const [isDraft,setIsDraft]=useState(false); const [videoUrl,setVideoUrl]=useState(""); const [thumbnailUrl,setThumbnailUrl]=useState(""); const [tags,setTags]=useState(""); const [privacyStatus,setPrivacyStatus]=useState<"private"|"unlisted"|"public">("private"); const [loading,setLoading]=useState(false); const [message,setMessage]=useState("");
 const selectedSource=useMemo(()=>contents.find(i=>i.id===sourceId),[contents,sourceId]);
 function chooseSource(id:string){setSourceId(id);const item=contents.find(r=>r.id===id);if(item){setTitle(item.title||item.product_title);setContent(item.content||"");}}
 function toggleChannel(id:string){setSelectedChannels(current=>current.includes(id)?current.filter(v=>v!==id):[...current,id]);}
 async function refreshJobs(){const response=await fetch("/api/publishing/jobs",{cache:"no-store"});const data=await response.json();if(data.success)setJobs(data.jobs||[]);}
 async function createJob(){setLoading(true);setMessage("");try{const response=await fetch("/api/publishing/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channels:selectedChannels,title,content,scheduledAt:new Date(scheduledAt).toISOString(),aiContentId:selectedSource?.id||null,payload:{isDraft,videoUrl,thumbnailUrl,tags:tags.split(",").map(v=>v.trim()).filter(Boolean),privacyStatus,sourceContentId:selectedSource?.id||null}})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||"게시 작업 등록 실패");setMessage(`${data.jobs?.length||0}개 채널을 게시 대기함에 등록했습니다.`);await refreshJobs();}catch(error){setMessage(error instanceof Error?error.message:"게시 작업 등록 실패");}finally{setLoading(false);}}
 async function runQueue(){setLoading(true);setMessage("");try{const response=await fetch("/api/publish/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({limit:20})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||"게시 실행 실패");setMessage(`${data.processed}개 작업을 처리했습니다.`);await refreshJobs();}catch(error){setMessage(error instanceof Error?error.message:"게시 실행 실패");}finally{setLoading(false);}}
 async function changeJob(id:string,action:"retry"|"cancel"){await fetch("/api/publishing/jobs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});await refreshJobs();}
 async function deleteJob(id:string){if(!window.confirm("이 게시 작업을 삭제할까요?"))return;await fetch(`/api/publishing/jobs?id=${encodeURIComponent(id)}`,{method:"DELETE"});await refreshJobs();}
 async function copyNaver(text?:string){if(!text)return;await navigator.clipboard.writeText(text);setMessage("네이버 게시용 제목·본문·태그를 복사했습니다.");}
 return <div className="admin-page"><div className="admin-top"><div><span className="eyebrow">SPRINT 5 · PUBLISH CENTER</span><h1>통합 게시센터</h1><p>Creative Studio 결과물을 YouTube·Blogger·네이버 블로그 게시 흐름으로 연결합니다.</p></div><button className="button button-primary" disabled={loading} onClick={runQueue}>예약 작업 지금 실행</button></div>
 {message&&<div className="alert alert-warning" style={{marginBottom:18}}>{message}</div>}
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.4fr) minmax(320px,.7fr)",gap:20,alignItems:"start"}}><section className="panel"><h2>새 다중 채널 게시</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",margin:"16px 0"}}>{channels.map(ch=><label key={ch.id} className="button button-light" style={{cursor:"pointer"}}><input type="checkbox" checked={selectedChannels.includes(ch.id)} onChange={()=>toggleChannel(ch.id)} /> {ch.label}</label>)}</div><div className="form-grid"><label className="field"><span>저장 콘텐츠</span><select value={sourceId} onChange={e=>chooseSource(e.target.value)}><option value="">직접 입력</option>{contents.map(i=><option key={i.id} value={i.id}>{i.title} · {i.product_title}</option>)}</select></label><label className="field"><span>예약 시간</span><input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} /></label><label className="field field-full"><span>제목</span><input value={title} onChange={e=>setTitle(e.target.value)} /></label><label className="field field-full"><span>본문·설명</span><textarea rows={12} value={content} onChange={e=>setContent(e.target.value)} /></label><label className="field field-full"><span>태그·라벨 (쉼표 구분)</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="AI, 재테크, 부업" /></label>{selectedChannels.includes("youtube")&&<><label className="field field-full"><span>완성 영상 URL</span><input value={videoUrl} onChange={e=>setVideoUrl(e.target.value)} placeholder="Supabase Storage의 mp4 공개 URL" /></label><label className="field"><span>썸네일 URL</span><input value={thumbnailUrl} onChange={e=>setThumbnailUrl(e.target.value)} /></label><label className="field"><span>공개 설정</span><select value={privacyStatus} onChange={e=>setPrivacyStatus(e.target.value as typeof privacyStatus)}><option value="private">비공개</option><option value="unlisted">일부 공개</option><option value="public">공개</option></select></label></>}{selectedChannels.includes("blogger")&&<label className="field"><span>Blogger 방식</span><span style={{display:"flex",gap:8,alignItems:"center",minHeight:44}}><input type="checkbox" checked={isDraft} onChange={e=>setIsDraft(e.target.checked)} /> 초안 저장</span></label>}</div><button className="button button-primary" disabled={loading||!title.trim()||!content.trim()||!selectedChannels.length||(selectedChannels.includes("youtube")&&!videoUrl.trim())} onClick={createJob}>선택 채널 게시 대기함에 추가</button></section>
 <section className="panel"><h2>연결 상태 안내</h2><div style={{display:"grid",gap:12,marginTop:16}}><div className="alert alert-info"><b>YouTube</b><br/>OAuth 연결 후 영상·제목·설명·태그·썸네일을 업로드합니다.</div><div className="alert alert-info"><b>Blogger</b><br/>공식 API로 HTML 본문·라벨·초안 또는 즉시 게시를 처리합니다.</div><div className="alert alert-info"><b>네이버</b><br/>공식 원격 글쓰기 API 대신 게시 패키지와 공유창을 생성합니다. 최종 발행은 대표님이 확인합니다.</div></div></section></div>
 <section className="panel" style={{marginTop:20}}><div className="admin-top" style={{marginBottom:12}}><div><h2>게시 큐와 이력</h2><p>실패 작업은 최대 3회까지 재시도할 수 있습니다.</p></div><button className="button button-light" onClick={refreshJobs}>새로고침</button></div><div className="table-wrap"><table><thead><tr><th>채널</th><th>제목</th><th>상태</th><th>예약</th><th>시도</th><th>결과</th><th>관리</th></tr></thead><tbody>{jobs.length?jobs.map(job=><tr key={job.id}><td>{channelLabel[job.channel]||job.channel}</td><td><b>{job.title}</b></td><td>{statusLabel[job.status]||job.status}</td><td>{new Date(job.scheduled_at).toLocaleString("ko-KR")}</td><td>{job.attempts||0}</td><td>{job.payload?.resultUrl?<a href={job.payload.resultUrl} target="_blank" rel="noreferrer">열기</a>:job.last_error||job.payload?.resultMessage||"-"}{job.channel==="naver"&&job.payload?.naverPackage?.text&&<button className="button button-light" onClick={()=>copyNaver(job.payload?.naverPackage?.text)}>본문 복사</button>}</td><td style={{whiteSpace:"nowrap"}}>{(job.status==="retry"||job.status==="cancelled")&&<button className="button button-light" onClick={()=>changeJob(job.id,"retry")}>재시도</button>}{!["published","cancelled"].includes(job.status)&&<button className="button button-light" onClick={()=>changeJob(job.id,"cancel")}>취소</button>}<button className="button button-light" onClick={()=>deleteJob(job.id)}>삭제</button></td></tr>):<tr><td colSpan={7}>등록된 게시 작업이 없습니다.</td></tr>}</tbody></table></div></section></div>;
}
